name: setup
description: Sets up development environment
inputs:
  llvm-version:
    description: LLVM major version to install
    required: false
    default: "23"
outputs: {}
runs:
  using: composite
  steps:
    # spell-checker: disable-next-line
    - uses: swatinem/rust-cache@c676846f29d98ff6b0106d3608c7ffd4048af17b # v2.9.0
    - uses: homebrew/actions/setup-homebrew@master
    - run: tools/setup.sh
      shell: bash
      env:
        LLVM_VERSION: ${{ inputs.llvm-version }}
